---
apiVersion: v1
kind: Namespace
metadata:
  name: init-container-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  namespace: init-container-ns
  labels:
    pod: init-container
spec:
  containers:
  - name: main-container
    image: ubuntu
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-app-svc
    image: ubuntu
    command: ['sh', '-c', 'until getent hosts init-app-svc; do echo waiting for init-app-svc; sleep 2; done;']
  - name: init-db-svc
    image: ubuntu
    command: ['sh', '-c', 'until getent hosts init-db-svc; do echo waiting for init-db-svc; sleep 2; done;']
