---
apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-container
---
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: sidecar-container
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: main-nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log-path
      mountPath: /var/log/nginx
  - image: busybox
    name: sidecar-log-viewer
    command: ["sh","-c","while true; do cat /var/log/nginx/access.log; sleep 05; done"]
    volumeMounts:
    - name: log-path
      mountPath: /var/log/nginx

  volumes:
  - name: log-path
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar-svc
  namespace: sidecar-container
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
